### ISSUE TITLE
Group multiple data sources together into one part of tree in client

### ISSUE THREAD

**Issue by atlasmapper** [atlasmapper/atlasmapper#104]
Some data providers have multiple map servers, of multiple standards. An example of this if GeoScience Australia (http://www.ga.gov.au/data-pubs/web-services/ga-web-services). 

It would be nice to get able to present these multiple services as a since part of the "Add layers" tree so that the mess of servers does not complicate the user interface of the map client.

**Comment by gaellafond** [comment]
Fixed in v2.0.15
