### ISSUE TITLE
Improve the robustness of the GetCapabilities harvesting

### ISSUE THREAD

**Issue by elawrey** [atlasmapper/atlasmapper#108]
The AtlasMapper sometimes fails to cope fully with all variety of WMS services. This includes the linking of metadata records, support for time layers, and parsing issues. Some examples include: 
- http://svs.gsfc.nasa.gov/cgi-bin/wms?
- http://www.cmar.csiro.au/geoserver/wms
- https://gisservices.information.qld.gov.au/arcgis/services/PlanningCadastre/LandParcelPropertyFramework/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by elawrey** [comment]
Note: I found that removing the query parameters made the gisservices.information.qld.gov.au end point work. https://gisservices.information.qld.gov.au/arcgis/services/PlanningCadastre/LandParcelPropertyFramework/MapServer/WMSServer

**Comment by gaellafond** [comment]
Added better error reporting to the user in v2.0.0
